config/routes.rb
NetworkerNew::Application.routes.draw do
  get "update_events/new"

  resources :users do
	resources :basic_profiles
  end 
  
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  get "static_pages/home"

  get "static_pages/help"

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/profile',  to: 'sessions#get_profile'
  match '/connections',  to: 'sessions#get_connections'

  match '/linkedin',  to: 'sessions#linkedin'
  match '/feed', to: 'sessions#get_feed'
  match '/skills', to: 'sessions#get_skill'
  match '/skills_res', to: 'sessions#skills_search'
  match '/due_date_emails', to: 'sessions#get_due_date'
  match '/due_connections_result', to: 'sessions#connections_due_for_update'
  match '/congrats_mail', to: 'sessions#send_congrats_mail'
  get "sessions/callback"
  get "sessions/show"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  has_one :BasicProfile, :dependent => :destroy
  
  has_many :connections, foreign_key: "connection_id", dependent: :destroy
  #has_many :connections, dependent: :destroy
  #before_save { |user| user.email = email.downcase }
   before_save { email.downcase! }
   before_save :create_remember_token

  validates :name, presence: true
  validates :email, presence: true,  uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  
   # def set_BasicProfile_name= (name)
		# self.BasicProfile.first_name = name
    # end
	
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
	
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
   @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  
  
  def create
	@user = User.new(params[:user])
	if @user.save
	  sign_in @user
	  flash[:success] = "Welcome to Networker Elite!"
      redirect_to @user 
    else
      render 'new'
    end
  end
  
  # def profile
	# @user = User.find(params[:id])
	# @profile = @user.BasicProfile
	# rediret_to @profile
  # end
  
  
   private

   	
	def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
	
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<!DOCTYPE html>   

<div class=="center hero-unit">
<h1>Profile</h1>
	
</div>

app/views/users/show.html.erb
  <div class="center hero-unit">
    <%= @user.name %> 
	<%= link_to "Profile", profile_path, 
                                class: "btn btn-large btn-primary" %> 
    <%= link_to "Connections", connections_path, 
                                class: "btn btn-large btn-primary" %> 
	<%= link_to "Get LinkedIn updates", linkedin_path, 
                                class: "btn btn-large btn-primary" %>
	<%= link_to "Show netwrok feed", feed_path, 
                                class: "btn btn-large btn-primary" %>
	<%= link_to "Look for skills", skills_path, 
                                class: "btn btn-large btn-primary" %>
    <%= link_to "Due emails",  due_date_emails_path, 
								class: "btn btn-large btn-primary" %>
  </div>  