config/routes.rb
NetworkerNew::Application.routes.draw do
  get "update_events/new"

  resources :users do
	resources :basic_profiles
  end 
  
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  get "static_pages/home"

  get "static_pages/help"

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/profile',  to: 'sessions#get_profile'
  match '/connections',  to: 'sessions#get_connections'

  match '/linkedin',  to: 'sessions#linkedin'
  match '/feed', to: 'sessions#get_feed'
  match '/skills', to: 'sessions#get_skill'
  match '/skills_res', to: 'sessions#skills_search'
  match '/due_date_emails', to: 'sessions#get_due_date'
  match '/due_connections_result', to: 'sessions#connections_due_for_update'
  match '/congrats_mail', to: 'sessions#send_congrats_mail'
  get "sessions/callback"
  get "sessions/show"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NetworkerNew</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "LinkedIn Networker", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '#' %></li>
              <li><%= link_to "Help",    '#' %></li>
             			  
			  <% if signed_in? %>
			
						<li><%= link_to "Profile", current_user %></li>
					
						<li>
							<%= link_to "Sign out", signout_path, method: "delete" %>
						</li>
					</ul>
				</li>
			  <% else %>
				<li><%= link_to "Sign in", signin_path %></li>
			  <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
 <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>